# Generated by Django 4.2.7 on 2023-11-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='', verbose_name='이미지')),
                ('nickname', models.CharField(max_length=10, verbose_name='닉네임')),
                ('type', models.TextField(verbose_name='기념일 타입')),
                ('anniversary_yy', models.IntegerField(max_length=4, verbose_name='기념일 연')),
                ('anniversary_mm', models.CharField(max_length=2, verbose_name='기념일 월')),
                ('anniversary_dd', models.CharField(max_length=2, verbose_name='기념일 일')),
            ],
        ),
    ]
