# Generated by Django 4.2.7 on 2023-11-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='이메일')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=16, verbose_name='닉네임')),
                ('phone_number', models.CharField(max_length=11, verbose_name='전화번호')),
            ],
        ),
        migrations.AlterField(
            model_name='receiver',
            name='anniversary_dd',
            field=models.IntegerField(verbose_name='기념일 일'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='anniversary_mm',
            field=models.IntegerField(verbose_name='기념일 월'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='anniversary_yy',
            field=models.IntegerField(verbose_name='기념일 연'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='nickname',
            field=models.CharField(max_length=16, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='type',
            field=models.CharField(choices=[('birthday', '생일'), ('graduation', '졸업'), ('wedding', '결혼 기념일'), ('else', '그 외')], default='생일', max_length=10),
        ),
    ]
