# Generated by Django 4.2.7 on 2023-11-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_profile_alter_receiver_anniversary_dd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='이미지'),
        ),
    ]
