# Generated by Django 4.2.3 on 2023-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('today', 'Today'), ('simple', 'Simple'), ('special', 'Special'), ('cute', 'Cute')], default='today', max_length=10, verbose_name='카테고리'),
        ),
    ]
