# Generated by Django 4.2.3 on 2023-11-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='추천 여부'),
        ),
    ]
